name: Publish Package to npmjs
on:
    release:
        types: [published]
permissions: {}

jobs:
    build:
        permissions:
          contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - uses: mymindstorm/setup-emsdk@29ba4851d6da084ffdc1e0fc390efadbd75df9d1 # v11
            - name: Verify Emscripten
              run: emcc --version
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version: "lts/*"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
